namespace Utility
{
    public enum DbCollections
    {
        PurchaseListHubFeed,
        RentListHubFeed,
        UserContactDetails,
        NewHomesFeed,
        UserDetails,
        ArchiveLink,
        NewHomeArchiveLink,
        Communities,
        Coordinates,
        OfficeDetails,
        NewHomeCommunity
    }
    public enum Paging
    {
        PageSize = 5
    }

    public enum EntiyiType
    {
        	Winery                              =2084,
        	ATM                                 =3578,
        	TrainStation                       =4013,
        	CommuterRailStation               =4100,
        	BusStation                         =4170,
        	NamedPlace                         =4444,
        	FerryTerminal                      =4482,
        	Marina                              =4493,
        	PublicSportsAirport               =4580,
        	Airport                             =4581,
        	BusinessFacility                   =5000,
        	GroceryStore                       =5400,
        	AutoDealerships                    =5511,
        	AutoDealershipUsedCars           =5512,
        	PetrolGasolineStation             =5540,
        	MotorcycleDealership               =5571,
        	Restaurant                          =5800,
        	Nightlife                           =5813,
        	HistoricalMonument                 =5999,
        	Bank                                =6000,
        	Shopping                            =6512,
        	Hotel                               =7011,
        	SkiResort                          =7012,
        	OtherAccommodation                 =7013,
        	SkiLift                            =7014,
        	TouristInformation                 =7389,
        	RentalCarAgency                   =7510,
        	ParkingLot                         =7520,
        	ParkingGarageHouse                =7521,
        	ParkRide                         =7522,
        	AutoServiceMaintenance          =7538,
        	Cinema                              =7832,
        	RestArea                           =7897,
        	PerformingArts                     =7929,
        	BowlingCentre                      =7933,
        	SportsComplex                      =7940,
        	ParkRecreationArea                =7947,
        	Casino                              =7985,
        	ConventionExhibitionCentre        =7990,
        	GolfCourse                         =7992,
        	CivicCommunityCentre              =7994,
        	AmusementPark                      =7996,
        	SportsCentre                       =7997,
        	IceSkatingRink                    =7998,
        	TouristAttraction                  =7999,
        	Hospital                            =8060,
        	HigherEducation                    =8200,
        	School                              =8211,
        	Library                             =8231,
        	Museum                              =8410,
        	AutomobileClub                     =8699,
        	CityHall                           =9121,
        	CourtHouse                         =9211,
        	PoliceStation                      =9221,
        	Campground                          =9517,
        	TruckStopPlaza                    =9522,
        	GovernmentOffice                   =9525,
        	PostOffice                         =9530,
        	ConvenienceStore                   =9535,
        	ClothingStore                      =9537,
        	DepartmentStore                    =9545,
        	HomeSpecialtyStore                =9560,
        	Pharmacy                            =9565,
        	SpecialtyStore                     =9567,
        	SportingGoodsStore                =9568,
        	MedicalService                     =9583,
        	ResidentialAreaBuilding           =9590,
        	Cemetery                            =9591,
        	HighwayExit                        =9592,
        	TransportationService              =9593,
        	WeighStation                       =9710,
        	CargoCentre                        =9714,
        	MilitaryBase                       =9715,
        	AnimalPark                         =9718,
        	TruckDealership                    =9719,
        	HomeImprovementHardwareStore   =9986,
        	ConsumerElectronicsStore          =9987,
        	OfficeSupplyServicesStore      =9988,
        	IndustrialZone                     =9991,
        	PlaceofWorship                    =9992,
        	Embassy                             =9993,
        	CountyCouncil                      =9994,
        	Bookstore                           =9995,
        	CoffeeShop                         =9996,
        	Hamlet                              =9998,
        	BorderCrossing                     =9999
    }
}
